### ISSUE TITLE
Crystal 1.0.0 - incompatible version

### ISSUE THREAD

**Issue by PhitherekReborn** [splattael/libnotify.cr#4]
The following warning pops up when I try to build the project with this shard in dependencies:

Unable to satisfy the following requirements:

- `crystal (~> 0.33, >= 0.33.0)` required by `libnotify 0.3.2`
Failed to resolve dependencies, try updating incompatible shards or use --ignore-crystal-version as a workaround if no update is available.

The flag fixes it, but an upgrade would be nice.

**Comment by splattael** [comment]
@PhitherekReborn Please excuse the really late response :disappointed: I was on parental leave for a couple of months :sweat_smile: 

Great catch and thanks for reporting. @brodi1 fixed this issue via https://github.com/splattael/libnotify.cr/pull/5 :tada: 

I'll release the next minor soonish (a couple of minutes I hope - famous last words) :grin:

**Comment by splattael** [comment]
https://github.com/splattael/libnotify.cr/releases/tag/v0.4.0 is now release

**Comment by PhitherekReborn** [comment]
Better late than never :). Honestly I thought that the project was dead when looking at the commit history, glad to see you're still here maintaining it :).

**Comment by splattael** [comment]
@PhitherekReborn Yes, sometimes it's hard to tell whether a project is dead :skull: or its API just stable :sweat_smile: :grin:
